{{- if and .Values.ingress.enabled (eq .Values.kind "web") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common-service.fullname" . }}
  labels:
    {{- include "common-service.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "common-service.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
